### PR TITLE
Create Scramble_String.cpp

### PR DESCRIPTION
**Pull request by Amisha2093**
Leetcode Problem Scramble String in C++.

@muhtalhakhan, can you please accept the PR for issue #1.

### CODE REVIEW

**Comment by Amisha2093** [comment]
Hi @muhtalhakhan, can you please add my contribution in hacktoberfest23. As the repository is currently excluded from hacktoberfest23 on the website.

**Comment by muhtalhakhan** [comment]
@Amisha2093 I have added and made changes. Hope that it will reflected in 24 hours.

**Comment by Amisha2093** [comment]
> @Amisha2093 I have added and made changes. Hope that it will reflected in 24 hours.

Okay, thank you.

**Comment by Amisha2093** [comment]
Hi @muhtalhakhan, repository is still not included in hacktoberfest23, please check.

**Pull request merged**
